# ansible/monitoramento/tasks/main.yml
---
- name: Instalação e configuração do Prometheus
  ansible.builtin.import_tasks: 01-prometheus.yml
  tags:
    - monitoramento
    - monitoramento:prometheus

- name: Instalação e configuração do Loki
  ansible.builtin.import_tasks: 02-loki.yml
  tags:
    - monitoramento
    - monitoramento:loki