# ansible/kube_controller_manager/tasks/02-pki.yml
---
- name: Criar estrutura de diretórios para certificados
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: kubernetes
    group: kubernetes
    mode: "0750"
  loop:
    - /etc/kubernetes/pki/controller-manager

- name: Copiar certificados do kube-controller-manager
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: kubernetes
    group: kubernetes
    mode: "{{ item.mode }}"
    remote_src: true
  loop:
    - src: "{{ certs.ca_k8s.cert }}"
      dest: "/etc/kubernetes/pki/controller-manager/{{ certs.ca_k8s.cert | basename }}"
      mode: "0644"
    - src: "{{ certs.ca_k8s.chave }}"
      dest: "/etc/kubernetes/pki/controller-manager/{{ certs.ca_k8s.chave | basename }}"
      mode: "0600"
    - src: "{{ certs.kube_controller.cert | format(inventory_hostname) }}"
      dest: "/etc/kubernetes/pki/controller-manager/{{ certs.kube_controller.cert | format(inventory_hostname) | basename }}"
      mode: "0644"
    - src: "{{ certs.kube_controller.chave | format(inventory_hostname) }}"
      dest: "/etc/kubernetes/pki/controller-manager/{{ certs.kube_controller.chave | format(inventory_hostname) | basename }}"
      mode: "0600"
    - src: "{{ certs.service_account.chave }}"
      dest: "/etc/kubernetes/pki/controller-manager/{{ certs.service_account.chave | basename }}"
      mode: "0600"