# ansible/kube_controller_manager/tasks/main.yml
---
- name: Instalar kube-controller-manager
  ansible.builtin.import_tasks: 01-instalacao.yml
  tags:
    - kube-controller-manager
    - kube-controller-manager:pacotes

- name: Configurar certificados do kube-controller-manager
  ansible.builtin.import_tasks: 02-pki.yml
  tags:
    - kube-controller-manager
    - kube-controller-manager:pki

- name: Configurar serviço do kube-controller-manager
  ansible.builtin.import_tasks: 03-configuracao.yml
  tags:
    - kube-controller-manager
    - kube-controller-manager:configuracao