# ansible/monitoramento_nos/handlers/main.yml
---
- name: Reiniciar Node Exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: restarted
    daemon_reload: true

- name: Reiniciar Promtail
  ansible.builtin.systemd:
    name: promtail
    state: restarted
    daemon_reload: true