# ansible/ca-certs/tasks/2-cluster-ca.yml
---
- name: Verifica se os arquivos já existem
  ansible.builtin.stat:
    path: "{{ item }}"
  register: cluster_file_stats
  loop:
    - /vagrant/arquivos/cluster-ca.key
    - /vagrant/arquivos/cluster-ca.crt

- name: Gera um arquivo temporário para o CSR do Cluster CA
  ansible.builtin.tempfile:
    state: file
    prefix: k8s_ca
    suffix: csr
  register: temp_file
  when: not cluster_file_stats.results[0].stat.exists or not cluster_file_stats.results[1].stat.exists

- name: Gera a chave privada do Cluster CA
  community.crypto.openssl_privatekey:
    path: /vagrant/arquivos/cluster-ca.key
    type: "{{ tipo_chave_privada_k8s }}"
    state: present
  when: not cluster_file_stats.results[0].stat.exists

- name: Gera um CSR para o Cluster CA com as infos necessárias
  community.crypto.openssl_csr:
    basicConstraints_critical: true
    basic_constraints:
      - CA:TRUE
    common_name: cluster-ca.k8s-in-a-jar
    organization_name: Kubernetes in a Jar
    organizational_unit_name: Cluster CA
    key_usage:
      - keyCertSign
      - cRLSign
    keyUsage_critical: true
    subject_alt_name:
      - DNS:cluster.k8s.local
    extended_key_usage:
      - serverAuth
      - clientAuth
    extended_key_usage_critical: true
    subject:
      description: "CA para uso do cluster Kubernetes em geral - Apenas para Fins Educacionais"
    path: "{{ temp_file.path }}"
    privatekey_path: /vagrant/arquivos/cluster-ca.key
    state: present
  when: not cluster_file_stats.results[0].stat.exists or not cluster_file_stats.results[1].stat.exists

- name: Gera o certificado do Cluster CA
  community.crypto.x509_certificate:
    path: /vagrant/arquivos/cluster-ca.crt
    privatekey_path: /vagrant/arquivos/cluster-ca.key
    csr_path: "{{ temp_file.path }}"
    provider: selfsigned
    state: present
    selfsigned_not_before: "-1h"
    selfsigned_not_after: "+365d"
  when: not cluster_file_stats.results[1].stat.exists