---
- name: Gera um arquivo temporário para o CSR
  ansible.builtin.tempfile:
    state: file
    prefix: k8s_ca
    suffix: csr
  register: temp_file

- name: Gera a chave privada do CA
  community.crypto.openssl_privatekey:
    path: /vagrant/arquivos/cluster-ca.key
    type: "{{ tipo_chave_privada_k8s }}"
    state: present

- name: Gera um CSR para o Cluster CA com as infos necessárias
  community.crypto.openssl_csr:
    basicConstraints_critical: true
    basic_constraints:
      - CA:TRUE
    common_name: cluster-ca.k8s-in-a-jar
    organization_name: Kubernetes in a Jar
    organizational_unit_name: Cluster CA
    key_usage:
      - keyCertSign
      - cRLSign
    keyUsage_critical: true
    subject_alt_name:
      - DNS:cluster.k8s.local
    extended_key_usage:
      - serverAuth
      - clientAuth
    extended_key_usage_critical: true
    subject:
      description: "Cluster CA para Projeto Kubernetes in a Jar - Apenas para Fins Educacionais"
    path: "{{ temp_file.path }}"
    privatekey_path: /vagrant/arquivos/cluster-ca.key
    state: present

- name: Gera o certificado do Cluster CA
  community.crypto.x509_certificate:
    path: /vagrant/arquivos/cluster-ca.crt
    privatekey_path: /vagrant/arquivos/cluster-ca.key
    csr_path: "{{ temp_file.path }}"
    provider: selfsigned
    state: present
    selfsigned_not_before: "-1h"  
    selfsigned_not_after: "+365d"