# ansible/ca-certs/tasks/main.yml
---
- name: Instalação dos pré-requisitos para o CA
  ansible.builtin.import_tasks: '1-prereqs.yml'
  tags: ca-cert-prereqs

- name: "Criar CA principal do cluster - usado para comunicações seguras entre componentes do Kubernetes"
  ansible.builtin.import_tasks: '2-kubernetes-ca.yml'
  tags: kubernetes-ca

- name: "Criar Certificado Admin para uso com o Cluster"
  ansible.builtin.import_tasks: '3-kubernetes-admin.yml'
  tags: kubernetes-admin

- name: "Criar CA específico do etcd - usado exclusivamente para comunicações do banco de dados etcd"
  ansible.builtin.import_tasks: '4-etcd-ca.yml'
  tags: etcd-ca