# ansible/tls-ca/tasks/5-etcd-admin.yml
---
- name: Verifica se os arquivos do Etcd Admin j치 existem
  ansible.builtin.stat:
    path: "{{ item }}"
  register: etcd_admin_stats
  loop:
    - /vagrant/arquivos/etcd/etcd-admin.key
    - /vagrant/arquivos/etcd/etcd-admin.crt

- block:
  - name: Gera um arquivo tempor치rio para o CSR do Etcd Admin
    ansible.builtin.tempfile:
      state: file
      prefix: k8s_etcd_admin
      suffix: csr
    register: temp_file
    when: not etcd_admin_stats.results[0].stat.exists or not etcd_admin_stats.results[1].stat.exists

  - name: Gera a chave privada do Etcd Admin
    community.crypto.openssl_privatekey:
      path: /vagrant/arquivos/etcd/etcd-admin.key
      type: "{{ tipo_chave_privada_etcd }}"
      state: present
    when: not etcd_admin_stats.results[0].stat.exists

  - name: Gera um CSR para o Etcd Admin com as infos necess치rias
    community.crypto.openssl_csr:
      common_name: 'etcd-admin'
      extended_key_usage:
        - clientAuth
      path: "{{ temp_file.path }}"
      privatekey_path: /vagrant/arquivos/etcd/etcd-admin.key
      state: present
    when: not etcd_admin_stats.results[0].stat.exists or not etcd_admin_stats.results[1].stat.exists

  - name: Cria certificado TLS do Etcd Admin usando o Etcd CA
    community.crypto.x509_certificate:
      path: /vagrant/arquivos/etcd/etcd-admin.crt
      csr_path: "{{ temp_file.path }}"
      privatekey_path: /vagrant/arquivos/etcd/etcd-admin.key
      ownca_path: /vagrant/arquivos/etcd/etcd-ca.crt
      ownca_privatekey_path: /vagrant/arquivos/etcd/etcd-ca.key
      provider: ownca
      ownca_not_after: +365d
    when: not etcd_admin_stats.results[0].stat.exists or not etcd_admin_stats.results[1].stat.exists

  always:
    - name: Cleanup do arquivo tempor치rio
      ansible.builtin.file:
        path: "{{ temp_file.path }}"
        state: absent
      when:
        - temp_file is defined
        - temp_file.path is defined