# ansible/pki/defaults/main.yml
---
pki_regerar_certs: true

pki_tipo_curva: "Ed25519"
pki_algoritmo_hash: "sha512"

pki_validade_ca: 3650
pki_validade_cert: 365

pki_organizacao: "Kubernetes in a Jar"