# ansible/monitoramento/handlers/main.yml
---
- name: Reiniciar Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    daemon_reload: true

- name: Reiniciar Loki
  ansible.builtin.systemd:
    name: loki
    state: restarted
    daemon_reload: true