# ansible/pki/tasks/01-ca_etcd.yml
---
- name: Criar estrutura de diret칩rios para certificados do Etcd
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"
  loop:
    - "/vagrant/arquivos/pki"
    - "/vagrant/arquivos/pki/etcd"
  tags: ["ca_etcd", "diretorios"]

- name: Verificar se a CA do etcd j치 existe
  ansible.builtin.stat:
    path: "/vagrant/arquivos/pki/etcd/ca-etcd-chave.pem"
  register: ca_etcd_chave
  tags: ["ca_etcd", "verificacao_chave"]

- name: Gerar chave Ed25519 para CA do etcd
  community.crypto.openssl_privatekey:
    path: "/vagrant/arquivos/pki/etcd/ca-etcd-chave.pem"
    type: "{{ pki_tipo_curva }}"
    state: "present"
    force: "{{ pki_regerar_certs | bool }}"
  when: not ca_etcd_chave.stat.exists or pki_regerar_certs | bool
  tags: ["ca_etcd", "gerar_chave"]

- name: Verificar se o CSR do CA do etcd j치 existe
  ansible.builtin.stat:
    path: "/vagrant/arquivos/pki/etcd/ca-etcd.csr"
  register: ca_etcd_csr
  tags: ["ca_etcd", "verificacao_csr"]

- name: Gerar CSR para CA do etcd
  community.crypto.openssl_csr:
    path: "/vagrant/arquivos/pki/etcd/ca-etcd.csr"
    privatekey_path: "/vagrant/arquivos/pki/etcd/ca-etcd-chave.pem"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "etcd-ca"
    O: "{{ pki_organizacao }}"
    OU: "Autoridade Certificadora para o Etcd"
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    force: "{{ pki_regerar_certs | bool }}"
  when: not ca_etcd_csr.stat.exists or pki_regerar_certs | bool
  tags: ["ca_etcd", "gerar_csr"]

- name: Verificar se o certificado do CA do etcd j치 existe
  ansible.builtin.stat:
    path: "/vagrant/arquivos/pki/etcd/ca-etcd-cert.pem"
  register: ca_etcd_cert
  tags: ["ca_etcd", "verificacao_cert"]

- name: Gerar certificado autoassinado do CA do etcd
  community.crypto.x509_certificate:
    path: "/vagrant/arquivos/pki/etcd/ca-etcd-cert.pem"
    csr_path: "/vagrant/arquivos/pki/etcd/ca-etcd.csr"
    privatekey_path: "/vagrant/arquivos/pki/etcd/ca-etcd-chave.pem"
    provider: selfsigned
    selfsigned_not_after: "+{{ pki_validade_ca }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | bool }}"
  when: not ca_etcd_cert.stat.exists or pki_regerar_certs | bool
  tags: ["ca_etcd", "gerar_certificado"]
