# ansible/pki/tasks/01-ca_mtls_etcd.yml
---
- name: Verificar arquivos existentes da CA para mTLS do etcd
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - "{{ certs.ca_etcd.chave }}"
    - "{{ certs.ca_etcd.csr }}"
    - "{{ certs.ca_etcd.cert }}"
  register: ca_etcd_arquivos

- name: Gerar chave Ed25519 da CA para mTLS do etcd
  community.crypto.openssl_privatekey:
    path: "{{ certs.ca_etcd.chave }}"
    type: "{{ pki_tipo_curva }}"
    state: "present"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not ca_etcd_arquivos.results[0].stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Gerar CSR da CA para mTLS do etcd
  community.crypto.openssl_csr:
    path: "{{ certs.ca_etcd.csr }}"
    privatekey_path: "{{ certs.ca_etcd.chave }}"
    digest: "{{ pki_algoritmo_hash }}"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "etcd-ca"
    OU:
      - "{{ pki_organizacao }}"
      - "Autoridade Certificadora para o Etcd"
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
      - keyEncipherment
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not ca_etcd_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Gerar certificado autoassinado da CA para mTLS do etcd
  community.crypto.x509_certificate:
    path: "{{ certs.ca_etcd.cert }}"
    csr_path: "{{ certs.ca_etcd.csr }}"
    privatekey_path: "{{ certs.ca_etcd.chave }}"
    provider: selfsigned
    selfsigned_digest: "{{ pki_algoritmo_hash }}"
    selfsigned_not_after: "+{{ pki_validade_ca }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not ca_etcd_arquivos.results[2].stat.exists or (pki_regerar_certs | default(false) | bool)
