# ansible/pki/tasks/02-ca_kubernetes.yml
---
- name: Verificar arquivos existentes da CA para mTLS do etcd
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - "{{ certs.ca_k8s.chave }}"
    - "{{ certs.ca_k8s.csr }}"
    - "{{ certs.ca_k8s.cert }}"
  register: ca_k8s_arquivos

- name: Gerar chave Ed25519 para CA do kubernetes
  community.crypto.openssl_privatekey:
    path: "{{ certs.ca_k8s.chave }}"
    type: "{{ pki_tipo_curva }}"
    state: "present"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not ca_k8s_arquivos.results[0].stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Gerar CSR para CA do kubernetes
  community.crypto.openssl_csr:
    path: "{{ certs.ca_k8s.csr }}"
    privatekey_path: "{{ certs.ca_k8s.chave }}"
    digest: "{{ pki_algoritmo_hash }}"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "kubernetes-ca"
    OU:
      - "{{ pki_organizacao }}"
      - "Autoridade Certificadora para o Kubernetes"
    basic_constraints:
      - "CA:TRUE"
    basic_constraints_critical: true
    key_usage:
      - digitalSignature
      - keyCertSign
      - cRLSign
    key_usage_critical: true
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not ca_k8s_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Gerar certificado autoassinado da CA do kubernetes
  community.crypto.x509_certificate:
    path: "{{ certs.ca_k8s.cert }}"
    csr_path: "{{ certs.ca_k8s.csr }}"
    privatekey_path: "{{ certs.ca_k8s.chave }}"
    provider: selfsigned
    selfsigned_digest: "{{ pki_algoritmo_hash }}"
    selfsigned_not_after: "+{{ pki_validade_ca }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not ca_k8s_arquivos.results[2].stat.exists or (pki_regerar_certs | default(false) | bool)
