# ansible/pki/tasks/03-cert_mtls_etcd_apiserver_client.yml
---
- name: Verificar arquivos existentes da chave para cliente mTLS do apiserver para etcd
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - "{{ certs.etcd_apiserver_cliente.chave }}"
    - "{{ certs.etcd_apiserver_cliente.csr }}"
    - "{{ certs.etcd_apiserver_cliente.cert }}"
  register: etcd_apiserver_cliente_arquivos

- name: Gerar chave Ed25519 para cliente mTLS do apiserver para etcd
  community.crypto.openssl_privatekey:
    path: "{{ certs.etcd_apiserver_cliente.chave }}"
    type: "{{ pki_tipo_curva }}"
    state: "present"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not etcd_apiserver_cliente_arquivos.results[0].stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Gerar CSR para cliente mTLS do apiserver para etcd
  community.crypto.openssl_csr:
    path: "{{ certs.etcd_apiserver_cliente.csr }}"
    privatekey_path: "{{ certs.etcd_apiserver_cliente.chave }}"
    digest: "{{ pki_algoritmo_hash }}"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "etcd-apiserver-cliente"
    OU:
      - "{{ pki_organizacao }}"
      - "Cliente Etcd para API Server"
    key_usage:
      - digitalSignature
      - keyAgreement
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
    extended_key_usage_critical: true
    subject_alt_name: "{{ lookup('template', 'etcd_apiserver_cliente_san.j2') | from_yaml }}"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not etcd_apiserver_cliente_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Gerar certificado para cliente mTLS do apiserver para etcd
  community.crypto.x509_certificate:
    path: "{{ certs.etcd_apiserver_cliente.cert }}"
    csr_path: "{{ certs.etcd_apiserver_cliente.csr }}"
    provider: ownca
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_path: "{{ certs.ca_etcd.cert }}"
    ownca_privatekey_path: "{{ certs.ca_etcd.chave }}"
    ownca_not_after: "+{{ pki_validade_cert }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not etcd_apiserver_cliente_arquivos.results[2].stat.exists or (pki_regerar_certs | default(false) | bool)
