# ansible/pki/tasks/08-cert_kube_controller_manager.yml
---
- name: Verificar se a chave do kube-controller-manager já existe ({{ manager_host }})
  ansible.builtin.stat:
    path: "{{ certs.kube_controller.chave | format(manager_host) }}"
  register: controller_manager_chave

- name: Gerar chave Ed25519 para kube-controller-manager ({{ manager_host }})
  community.crypto.openssl_privatekey:
    path: "{{ certs.kube_controller.chave | format(manager_host) }}"
    type: "{{ pki_tipo_curva }}"
    state: "present"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not controller_manager_chave.stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Verificar se o CSR do kube-controller-manager já existe ({{ manager_host }})
  ansible.builtin.stat:
    path: "{{ certs.kube_controller.csr | format(manager_host) }}"
  register: controller_manager_csr

- name: Gerar CSR para kube-controller-manager ({{ manager_host }})
  community.crypto.openssl_csr:
    path: "{{ certs.kube_controller.csr | format(manager_host) }}"
    privatekey_path: "{{ certs.kube_controller.chave | format(manager_host) }}"
    digest: "{{ pki_algoritmo_hash }}"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "system:kube-controller-manager"
    O: "system:kube-controller-manager"
    OU: "Kubernetes in a Jar"
    key_usage:
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
    extended_key_usage_critical: true
    subject_alt_name: "{{ lookup('template', 'kube_controller_manager_san.j2') | from_yaml }}"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not controller_manager_csr.stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Verificar se o certificado do kube-controller-manager já existe ({{ manager_host }})
  ansible.builtin.stat:
    path: "{{ certs.kube_controller.cert | format(manager_host) }}"
  register: controller_manager_cert

- name: Gerar certificado do kube-controller-manager ({{ manager_host }})
  community.crypto.x509_certificate:
    path: "{{ certs.kube_controller.cert | format(manager_host) }}"
    csr_path: "{{ certs.kube_controller.csr | format(manager_host) }}"
    provider: ownca
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_path: "{{ certs.ca_k8s.cert }}"
    ownca_privatekey_path: "{{ certs.ca_k8s.chave }}"
    ownca_not_after: "+{{ pki_validade_cert }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not controller_manager_cert.stat.exists or (pki_regerar_certs | default(false) | bool)