# ansible/pki/tasks/08-cert_kube_controller_manager.yml
---
- name: Verificar arquivos existentes do kube-controller-manager ({{ manager_host }})
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - "{{ certs.kube_controller.chave | format(manager_host) }}"
    - "{{ certs.kube_controller.csr | format(manager_host) }}"
    - "{{ certs.kube_controller.cert | format(manager_host) }}"
  register: kube_controller_arquivos

- name: Gerar chave Ed25519 para kube-controller-manager ({{ manager_host }})
  community.crypto.openssl_privatekey:
    path: "{{ certs.kube_controller.chave | format(manager_host) }}"
    type: "{{ pki_tipo_curva }}"
    state: "present"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not kube_controller_arquivos.results[0].stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Gerar CSR para kube-controller-manager ({{ manager_host }})
  community.crypto.openssl_csr:
    path: "{{ certs.kube_controller.csr | format(manager_host) }}"
    privatekey_path: "{{ certs.kube_controller.chave | format(manager_host) }}"
    digest: "{{ pki_algoritmo_hash }}"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "system:kube-controller-manager"
    O: "system:kube-controller-manager"
    OU:
      - "{{ pki_organizacao }}"
      - "Kube Controller Manager"
    key_usage:
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
    extended_key_usage_critical: true
    subject_alt_name: "{{ lookup('template', 'kube_controller_manager_san.j2') | from_yaml }}"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not kube_controller_arquivos.results[1].stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Gerar certificado do kube-controller-manager ({{ manager_host }})
  community.crypto.x509_certificate:
    path: "{{ certs.kube_controller.cert | format(manager_host) }}"
    csr_path: "{{ certs.kube_controller.csr | format(manager_host) }}"
    provider: ownca
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_path: "{{ certs.ca_k8s.cert }}"
    ownca_privatekey_path: "{{ certs.ca_k8s.chave }}"
    ownca_not_after: "+{{ pki_validade_cert }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not kube_controller_arquivos.results[2].stat.exists or (pki_regerar_certs | default(false) | bool)
