# ansible/pki/tasks/10-cert_kube_proxy.yml
---
- name: Verificar se a chave do kube-proxy já existe ({{ node_host }})
  ansible.builtin.stat:
    path: "{{ certs.kube_proxy.chave | format(node_host) }}"
  register: kube_proxy_chave

- name: Gerar chave Ed25519 para kube-proxy ({{ node_host }})
  community.crypto.openssl_privatekey:
    path: "{{ certs.kube_proxy.chave | format(node_host) }}"
    type: "{{ pki_tipo_curva }}"
    state: "present"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not kube_proxy_chave.stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Verificar se o CSR do kube-proxy já existe ({{ node_host }})
  ansible.builtin.stat:
    path: "{{ certs.kube_proxy.csr | format(node_host) }}"
  register: kube_proxy_csr

- name: Gerar CSR para kube-proxy ({{ node_host }})
  community.crypto.openssl_csr:
    path: "{{ certs.kube_proxy.csr | format(node_host) }}"
    privatekey_path: "{{ certs.kube_proxy.chave | format(node_host) }}"
    digest: "{{ pki_algoritmo_hash }}"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "system:kube-proxy"
    O: "system:node-proxier"
    OU:
      - "{{ pki_organizacao }}"
      - "Kube Proxy"
    key_usage:
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
    extended_key_usage_critical: true
    subject_alt_name: "{{ lookup('template', 'kube_proxy_san.j2') | from_yaml }}"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not kube_proxy_csr.stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Verificar se o certificado do kube-proxy já existe ({{ node_host }})
  ansible.builtin.stat:
    path: "{{ certs.kube_proxy.cert | format(node_host) }}"
  register: kube_proxy_cert

- name: Gerar certificado do kube-proxy ({{ node_host }})
  community.crypto.x509_certificate:
    path: "{{ certs.kube_proxy.cert | format(node_host) }}"
    csr_path: "{{ certs.kube_proxy.csr | format(node_host) }}"
    provider: ownca
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_path: "{{ certs.ca_k8s.cert }}"
    ownca_privatekey_path: "{{ certs.ca_k8s.chave }}"
    ownca_not_after: "+{{ pki_validade_cert }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not kube_proxy_cert.stat.exists or (pki_regerar_certs | default(false) | bool)