# ansible/pki/tasks/11-cert_service_account.yml
---
- name: Verificar se a chave do service-account já existe
  ansible.builtin.stat:
    path: "{{ certs.service_account.chave }}"
  register: service_account_chave

- name: Gerar chave RSA para service-account
  community.crypto.openssl_privatekey:
    path: "{{ certs.service_account.chave }}"
    type: "RSA"
    size: 2048
    state: "present"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not service_account_chave.stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Verificar se o CSR do service-account já existe
  ansible.builtin.stat:
    path: "{{ certs.service_account.csr }}"
  register: service_account_csr

- name: Gerar CSR para service-account
  community.crypto.openssl_csr:
    path: "{{ certs.service_account.csr }}"
    privatekey_path: "{{ certs.service_account.chave }}"
    digest: "sha256"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "service-accounts"
    O: "{{ pki_organizacao }}"
    OU:
      - "{{ pki_organizacao }}"
      - "Conta de Serviço do Kubernetes"
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not service_account_csr.stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Verificar se o certificado do service-account já existe
  ansible.builtin.stat:
    path: "{{ certs.service_account.cert }}"
  register: service_account_cert

- name: Gerar certificado do service-account
  community.crypto.x509_certificate:
    path: "{{ certs.service_account.cert }}"
    csr_path: "{{ certs.service_account.csr }}"
    provider: ownca
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_path: "{{ certs.ca_k8s.cert }}"
    ownca_privatekey_path: "{{ certs.ca_k8s.chave }}"
    ownca_not_after: "+{{ pki_validade_cert }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not service_account_cert.stat.exists or (pki_regerar_certs | default(false) | bool)