# ansible/pki/tasks/12-cert_admin.yml
---
- name: Verificar se a chave do admin já existe
  ansible.builtin.stat:
    path: "{{ certs.k8s_admin.chave }}"
  register: admin_chave

- name: Gerar chave Ed25519 para admin
  community.crypto.openssl_privatekey:
    path: "{{ certs.k8s_admin.chave }}"
    type: "{{ pki_tipo_curva }}"
    state: "present"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not admin_chave.stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Verificar se o CSR do admin já existe
  ansible.builtin.stat:
    path: "{{ certs.k8s_admin.csr }}"
  register: admin_csr

- name: Gerar CSR para admin
  community.crypto.openssl_csr:
    path: "{{ certs.k8s_admin.csr }}"
    privatekey_path: "{{ certs.k8s_admin.chave }}"
    digest: "{{ pki_algoritmo_hash }}"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "kubernetes-admin"
    O: "system:masters"
    OU:
      - "{{ pki_organizacao }}"
      - "Administrador do Cluster Kubernetes"
    key_usage:
      - digitalSignature
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
    extended_key_usage_critical: true
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not admin_csr.stat.exists or (pki_regerar_certs | default(false) | bool)

- name: Verificar se o certificado do admin já existe
  ansible.builtin.stat:
    path: "{{ certs.k8s_admin.cert }}"
  register: admin_cert

- name: Gerar certificado do admin
  community.crypto.x509_certificate:
    path: "{{ certs.k8s_admin.cert }}"
    csr_path: "{{ certs.k8s_admin.csr }}"
    provider: ownca
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_path: "{{ certs.ca_k8s.cert }}"
    ownca_privatekey_path: "{{ certs.ca_k8s.chave }}"
    ownca_not_after: "+{{ pki_validade_cert }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | default(false) | bool }}"
  when: not admin_cert.stat.exists or (pki_regerar_certs | default(false) | bool)