# ansible/pki/tasks/12-cert_service_account.yml
---
- name: Verificar se a chave do service-account já existe
  ansible.builtin.stat:
    path: "/vagrant/arquivos/pki/kubernetes/service-account-chave.pem"
  register: service_account_chave
  tags: ["service_account", "verificacao_chave"]

- name: Gerar chave RSA para service-account
  community.crypto.openssl_privatekey:
    path: "/vagrant/arquivos/pki/kubernetes/service-account-chave.pem"
    type: "RSA"
    size: 2048
    state: "present"
    force: "{{ pki_regerar_certs | bool }}"
  when: not service_account_chave.stat.exists or pki_regerar_certs | bool
  tags: ["service_account", "gerar_chave"]

- name: Verificar se o CSR do service-account já existe
  ansible.builtin.stat:
    path: "/vagrant/arquivos/pki/kubernetes/service-account.csr"
  register: service_account_csr
  tags: ["service_account", "verificacao_csr"]

- name: Gerar CSR para service-account
  community.crypto.openssl_csr:
    path: "/vagrant/arquivos/pki/kubernetes/service-account.csr"
    privatekey_path: "/vagrant/arquivos/pki/kubernetes/service-account-chave.pem"
    digest: "sha256"
    mode: "0600"
    owner: "root"
    group: "root"
    CN: "service-accounts"
    O: "{{ pki_organizacao }}"
    OU: "Kubernetes Service Accounts"
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    force: "{{ pki_regerar_certs | bool }}"
  when: not service_account_csr.stat.exists or pki_regerar_certs | bool
  tags: ["service_account", "gerar_csr"]

- name: Verificar se o certificado do service-account já existe
  ansible.builtin.stat:
    path: "/vagrant/arquivos/pki/kubernetes/service-account-cert.pem"
  register: service_account_cert
  tags: ["service_account", "verificacao_cert"]

- name: Gerar certificado do service-account
  community.crypto.x509_certificate:
    path: "/vagrant/arquivos/pki/kubernetes/service-account-cert.pem"
    csr_path: "/vagrant/arquivos/pki/kubernetes/service-account.csr"
    provider: ownca
    ownca_digest: "{{ pki_algoritmo_hash }}"
    ownca_path: "/vagrant/arquivos/pki/kubernetes/ca-kubernetes-cert.pem"
    ownca_privatekey_path: "/vagrant/arquivos/pki/kubernetes/ca-kubernetes-chave.pem"
    ownca_not_after: "+{{ pki_validade_cert }}d"
    mode: "0644"
    owner: "root"
    group: "root"
    force: "{{ pki_regerar_certs | bool }}"
  when: not service_account_cert.stat.exists or pki_regerar_certs | bool
  tags: ["service_account", "gerar_certificado"]