# ansible/pki/tasks/limpeza.yml
---
- name: Localizar todos os arquivos CSR
  ansible.builtin.find:
    paths: "{{ pki_dir }}"
    patterns: "*.csr"
    recurse: true
  register: arquivos_csr
  when: pki_remover_csr | default(false) | bool

- name: Remover arquivos CSR encontrados
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ arquivos_csr.files }}"
  when:
    - pki_remover_csr | default(false) | bool
    - arquivos_csr.files is defined
  loop_control:
    label: "Removendo {{ item.path | basename }}"