# ansible/pki/tasks/main.yml
---
- name: Criar CA do etcd
  ansible.builtin.include_tasks: 01-ca_etcd.yml
  tags:
    - pki
    - pki:ca
    - pki:etcd
    - pki:etcd:ca

- name: Criar CA do Kubernetes
  ansible.builtin.include_tasks: 02-ca_kubernetes.yml
  tags:
    - pki
    - pki:ca
    - pki:k8s
    - pki:k8s:ca

- name: Criar certificado cliente HAProxy para Etcd
  ansible.builtin.include_tasks: 03-cert_haproxy_cliente_etcd.yml
  tags:
    - pki
    - pki:etcd
    - pki:etcd:cliente
    - pki:etcd:haproxy

- name: Criar certificado cliente API Server para Etcd
  ansible.builtin.include_tasks: 04-cert_apiserver_cliente_etcd.yml
  tags:
    - pki
    - pki:etcd
    - pki:etcd:cliente
    - pki:etcd:apiserver

- name: Criar certificados dos servidores Etcd
  ansible.builtin.include_tasks: 05-cert_etcd_server.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:etcd
    - pki:etcd:server

- name: Criar certificados dos peers Etcd
  ansible.builtin.include_tasks: 06-cert_etcd_peer.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:etcd
    - pki:etcd:peer

- name: Criar certificados dos Kubelets
  ansible.builtin.include_tasks: 08-cert_kubelet.yml
  loop: "{{ groups['k8s_nodes'] }}"
  loop_control:
    loop_var: node_host
  tags:
    - pki
    - pki:k8s
    - pki:k8s:kubelet

# - name: Criar certificados dos servidores etcd
#   ansible.builtin.import_tasks: 02-cert_etcd_servers.yml
#   tags:
#     - pki
#     - pki:etcd
#     - pki:etcd:server

# - name: Criar certificado cliente etcd
#   ansible.builtin.import_tasks: 03-cert_etcd_client.yml
#   tags:
#     - pki
#     - pki:etcd
#     - pki:etcd:client

# - name: Criar certificado do API Server
#   ansible.builtin.import_tasks: 05-cert_apiserver.yml
#   tags:
#     - pki
#     - pki:k8s
#     - pki:k8s:apiserver

# Monitoramento de certificados (não roda por padrão)
- name: Monitorar certificados
  ansible.builtin.import_tasks: relatorio-certs.yml
  tags: 
    - never
    - pki:monitor