# ansible/pki/tasks/main.yml
---
- name: Executar pre-tasks de estrutura de diretórios
  ansible.builtin.include_tasks: pre-tasks.yml
  tags:
    - pki
    - pki:pre
    - pki:dirs

- name: Criar CA para mTLS do etcd
  ansible.builtin.include_tasks: 01-ca_mtls_etcd.yml
  tags:
    - pki
    - pki:ca
    - pki:etcd
    - pki:etcd:ca

- name: Criar CA do Kubernetes
  ansible.builtin.include_tasks: 02-ca_kubernetes.yml
  tags:
    - pki
    - pki:ca
    - pki:k8s
    - pki:k8s:ca

- name: Criar certificado cliente mTLS do kube-apiserver para etcd
  ansible.builtin.include_tasks: 03-cert_mtls_etcd_apiserver_client.yml
  tags:
    - pki
    - pki:etcd
    - pki:etcd:cliente
    - pki:etcd:apiserver

- name: Criar certificados para mTLS dos servidores etcd
  ansible.builtin.include_tasks: 04-cert_mtls_etcd_server.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:etcd
    - pki:etcd:server

- name: Criar certificados para mTLS dos peers etcd
  ansible.builtin.include_tasks: 05-cert_mtls_etcd_peer.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:etcd
    - pki:etcd:peer

- name: Criar certificados dos kube-apiservers
  ansible.builtin.include_tasks: 06-cert_kube_apiserver.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:k8s
    - pki:k8s:apiserver

- name: Criar certificados dos Kubelets
  ansible.builtin.include_tasks: 07-cert_kubelet.yml
  loop: "{{ groups['k8s_nodes'] }}"
  loop_control:
    loop_var: node_host
  tags:
    - pki
    - pki:k8s
    - pki:k8s:kubelet

- name: Criar certificados dos controller-managers
  ansible.builtin.include_tasks: 08-cert_kube_controller_manager.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:k8s
    - pki:k8s:controller-manager

- name: Criar certificados dos kube-schedulers
  ansible.builtin.include_tasks: 09-cert_kube_scheduler.yml
  loop: "{{ groups['managers'] }}"
  loop_control:
    loop_var: manager_host
  tags:
    - pki
    - pki:k8s
    - pki:k8s:scheduler

- name: Criar certificados dos kube-proxies
  ansible.builtin.include_tasks: 10-cert_kube_proxy.yml
  loop: "{{ groups['k8s_nodes'] }}"
  loop_control:
    loop_var: node_host
  tags:
    - pki
    - pki:k8s
    - pki:k8s:proxy

- name: Criar certificado do service account
  ansible.builtin.include_tasks: 11-cert_service_account.yml
  tags:
    - pki
    - pki:k8s
    - pki:k8s:service-account

- name: Criar certificado do admin
  ansible.builtin.include_tasks: 12-cert_admin.yml
  tags:
    - pki
    - pki:k8s
    - pki:k8s:admin
    - pki:admin