---
# Monitoramento do estado dos certificados
- name: Procurar todos os certificados
  ansible.builtin.find:
    paths: "{{ pki_pasta_base }}"
    patterns: "*-cert.pem"
    recurse: yes
  register: certificados_encontrados
  tags: ["monitor", "descoberta"]

- name: Verificar informações dos certificados
  ansible.builtin.command:
    cmd: >-
      openssl x509 -in {{ item.path }} -noout 
      -subject -issuer -dates -fingerprint
  register: detalhes_certificados
  changed_when: false
  loop: "{{ certificados_encontrados.files }}"
  loop_control:
    label: "{{ item.path }}"
  tags: ["monitor", "inspecao"]

- name: Calcular dias até expiração
  ansible.builtin.shell:
    cmd: >-
      openssl x509 -in {{ item.path }} -noout -enddate | 
      cut -d= -f2- | 
      xargs -I{} date -d "{}" +%s
  register: datas_expiracao
  changed_when: false
  loop: "{{ certificados_encontrados.files }}"
  loop_control:
    label: "{{ item.path }}"
  tags: ["monitor", "expiracao"]

- name: Preparar relatório
  ansible.builtin.set_fact:
    relatorio_certificados: "{{ relatorio_certificados | default([]) + [{ 
      'caminho': item.0.path,
      'detalhes': item.1.stdout,
      'timestamp_expiracao': item.2.stdout | int,
      'dias_restantes': ((item.2.stdout | int - ansible_date_time.epoch | int) / 86400) | round
    }] }}"
  loop: "{{ certificados_encontrados.files | zip(detalhes_certificados.results, datas_expiracao.results) | list }}"
  loop_control:
    label: "{{ item.0.path }}"
  tags: ["monitor", "relatorio"]

- name: Gerar relatório em arquivo
  ansible.builtin.template:
    src: relatorio-certificados.j2
    dest: "{{ pki_pasta_base }}/status-certificados.txt"
    mode: '0644'
  tags: ["monitor", "arquivo-relatorio"]