# ansible/etcd/tasks/02-pki.yml
---
- name: Criar estrutura de diretórios para certificados do etcd
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
    mode: "0750"
  loop:
    - /etc/etcd/pki/server
    - /etc/etcd/pki/peer
    - /etc/etcd/pki/ca

# Certificados CA (comuns a todos)
- name: Copiar certificado CA
  ansible.builtin.copy:
    src: "{{ certs.ca_etcd.cert }}"
    dest: "/etc/etcd/pki/ca/ca.pem"
    owner: etcd
    group: etcd
    mode: "0644"
    remote_src: true

# Certificados do servidor (específico do nó)
- name: Copiar certificados do servidor
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: etcd
    group: etcd
    mode: "0600"
    remote_src: true
  loop:
    - src: "{{ certs.etcd_server.cert | format(inventory_hostname) }}"
      dest: "/etc/etcd/pki/server/server-cert.pem"
    - src: "{{ certs.etcd_server.chave | format(inventory_hostname) }}"
      dest: "/etc/etcd/pki/server/server-key.pem"

# Certificados peer (todos os certificados para comunicação mútua)
- name: Copiar certificados peer do nó atual
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: etcd
    group: etcd
    mode: "0600"
    remote_src: true
  loop:
    - src: "{{ certs.etcd_peer.cert | format(inventory_hostname) }}"
      dest: "/etc/etcd/pki/peer/{{ inventory_hostname }}-cert.pem"
    - src: "{{ certs.etcd_peer.chave | format(inventory_hostname) }}"
      dest: "/etc/etcd/pki/peer/{{ inventory_hostname }}-key.pem"

- name: Copiar certificados peer dos outros nós
  ansible.builtin.copy:
    src: "{{ certs.etcd_peer.cert | format(item) }}"
    dest: "/etc/etcd/pki/peer/{{ item }}-cert.pem"
    owner: etcd
    group: etcd
    mode: "0644"
    remote_src: true
  loop: "{{ groups['managers'] }}"
  when: item != inventory_hostname

- name: Criar arquivo do secret JWT para etcd
  copy:
    content: "{{ etcd_jwt_token | hash('sha256') }}"
    dest: "/etc/etcd/jwt-secret"
    mode: '0600'
    owner: etcd
    group: etcd