# ansible/etcd/tasks/main.yml
---
- name: Executar pre-tasks de estrutura de diretórios
  ansible.builtin.include_tasks: pre-tasks.yml
  tags:
    - etcd
    - etcd:pre

- name: Instalação do etcd
  ansible.builtin.import_tasks: 01-instalacao.yml
  tags:
    - etcd
    - etcd:pacotes

- name: Instalação dos certificados gerados
  ansible.builtin.import_tasks: 02-pki.yml
  tags:
    - etcd
    - etcd:pki

- name: Aplicação das configurações e inicialização do cluster etcd
  ansible.builtin.import_tasks: 03-configuracao.yml
  tags:
    - etcd
    - etcd:configuracao