# ansible/sistema/tasks/1-base.yml
---
- name: Configura o TZ para o Brasil
  community.general.timezone:
    name: America/Sao_Paulo

- name: Configurar locale padrão
  ansible.builtin.locale_gen:
    name: pt_BR.UTF-8
    state: present

- name: Habilita o repositório backports
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian bookworm-backports main contrib non-free non-free-firmware
    filename: backports
    state: present

- name: Atualizar cache do apt
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Atualiza os pacotes da distribuição
  ansible.builtin.apt:
    upgrade: 'dist'
    #default_release: "bookworm-backports"
  when: atualiza_sistema == "all"

- name: Aplica somente atualizações de segurança
  ansible.builtin.apt:
    upgrade: 'safe'
    #default_release: "bookworm-backports"
  when: atualiza_sistema == "patch"

- name: Cria registros DNS entre as máquinas do cluster
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item]['ansible_host'] }} {{ item }}"
    state: present
  with_items: "{{ groups['todos'] }}"

- name: Instala pacotes base para o Playbook
  ansible.builtin.apt:
    name:
      - ufw
    state: present

- name: Instalar Tailspin para facilitar a leitura de logs
  unarchive:
    src: https://github.com/bensadeh/tailspin/releases/download/4.0.0/tailspin-x86_64-unknown-linux-musl.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'

- name: Garante a existência da pasta do CA em todas as máquinas
  ansible.builtin.file:
    path: /etc/kubernetes/pki
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Garante a existência da pasta de temporários
  ansible.builtin.file:
    path: /vagrant/arquivos/tmp
    state: directory
    mode: '0755'

- name: Configura as políticas padrão do UFW
  ansible.builtin.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }

- name: Libera o SSH (porta 22) em todas as interfaces
  ansible.builtin.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Libera todo tráfego da rede 172.24.0.0/16
  ansible.builtin.ufw:
    rule: allow
    src: 172.24.0.0/16

- name: Ativa o UFW
  ansible.builtin.ufw:
    state: enabled