# ansible/k8s-base/tasks/1-prereqs.yml
---
- name: Habilita o IP Forwarding permamentemente
  ansible.builtin.copy:
    content: net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/20-ipforward.conf
    mode: "0644"
  notify: Reload sysctl

- name: Garante que o python3-pip está instalado
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip