# ansible/k8s-base/tasks/1-prereqs.yml
---
- name: Garante que o python3-pip está instalado
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip

- name: Desabilitar swap
  ansible.builtin.command:
    cmd: swapoff -a
  changed_when: false

- name: Remover entrada de swap do /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s.*)'
    replace: '# \1'

- name: Criar arquivo de configuração para módulos do kernel
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
    mode: "0644"
    owner: root
    group: root

- name: Carregar módulo overlay
  ansible.builtin.modprobe:
    name: overlay
    state: present

- name: Carregar módulo br_netfilter
  ansible.builtin.modprobe:
    name: br_netfilter
    state: present

- name: Criar arquivo de configuração sysctl para Kubernetes
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    mode: "0644"
    owner: root
    group: root

- name: Habilita o IP Forwarding permamentemente
  ansible.builtin.copy:
    content: net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/20-ipforward.conf
    mode: "0644"
    owner: root
    group: root
  notify: Reload sysctl