---
- name: Configurações base para todas as máquinas
  hosts: todos
  become: true
  gather_facts: true
  roles:
    - role: sistema

# - name: Configurar o Load Balancer
#   hosts: k8s_lb
#   become: true
#   gather_facts: true
#   roles:
#     - sistema

- name: Configurar nodes Kubernetes (comum para workers e managers)
  hosts: k8s_nodes
  become: true
  roles:
    - role: pre-requisitos

# - name: Configurar Kubernetes Manager
#   hosts: k8s_managers
#   become: true
#   roles:
#     - sistema

# - name: Configurar Kubernetes Workers
#   hosts: k8s_workers
#   become: true
#   roles:
#     - sistema