# ansible/playbook.yml
---
- name: Configurações base para todas as máquinas
  hosts: todos
  become: true
  gather_facts: true
  roles:
    - role: sistema
      tags:
        - sistema
        - todas

- name: Configurações do Load Balancer e geração das chaves dos CAs
  hosts: loadbalancers
  become: true
  gather_facts: true
  roles:
    - role: pki
      run_once: true
      tags:
        - pki
        - todas

    - role: haproxy
      tags:
        - haproxy
        - todas

    - role: pki_monitor
      run_once: true
      tags:
        - pki:monitor
        - never

- name: Configurações do cluster etcd
  hosts: managers
  become: true
  gather_facts: true
  roles:
    - role: etcd
      tags:
        - etcd
        - todas
    
- name: Configuração do kube-apiserver
  hosts: managers
  become: true
  gather_facts: true
  serial: 1
  roles:
    - role: kube_apiserver
      tags:
        - kube_apiserver
        - todas

# - name: Configurar nodes Kubernetes (comum para workers e managers)
#   hosts: k8s_nodes
#   become: true
#   gather_facts: true
#   vars_files:
#     - vars/cert.yml
#   roles:
#     - role: k8s-base
#     - role: tls-certs
#       tags: ['certs-kubelet']

# - name: Configurar Kubernetes Control Planes
#   hosts: managers
#   become: true
#   gather_facts: true
#   vars_files:
#     - vars/cert.yml
#   roles:
#     - role: tls-certs
#       run_once: true
#       tags: ['certs-apiserver']

# - name: Configurar Kubernetes Workers
#   hosts: workers
#   become: true
#   roles:
#     - sistema