# ansible/playbook.yml
---
- name: Configurações base para todas as máquinas
  hosts: todos
  become: true
  gather_facts: true
  roles:
    - role: sistema

- name: Configurações do Load Balancer e geração das chaves dos CAs
  hosts: loadbalancers
  become: true
  gather_facts: true
  vars_files:
    - vars/lb.yml
    - vars/cert.yml
    - vars/k8s.yml
  roles:
    - tls-ca
    - haproxy

- name: Configurar nodes Kubernetes (comum para workers e managers)
  hosts: k8s_nodes
  become: true
  roles:
    - role: k8s-base

# - name: Configurar Kubernetes Manager
#   hosts: managers
#   become: true
#   roles:
#     - sistema

# - name: Configurar Kubernetes Workers
#   hosts: workers
#   become: true
#   roles:
#     - sistema