# ansible/k8s_base/tasks/1-prereqs.yml
---
- name: Desabilitar swap
  ansible.builtin.command:
    cmd: swapoff -a
  changed_when: false

- name: Remover entrada de swap do /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s.*)'
    replace: '# \1'

- name: Criar usuário kubernetes
  ansible.builtin.user:
    name: kubernetes
    system: true
    shell: /usr/sbin/nologin
    home: /var/lib/kubernetes
    create_home: false

- name: Criar diretórios do Kubernetes no padrão Debian
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/kubernetes
    - /etc/kubernetes/pki
    - /var/lib/kubernetes
    - /var/log/kubernetes

- name: Ajustar permissões dos diretórios
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: kubernetes
    group: kubernetes
    mode: "{{ item.mode }}"
  loop:
    - path: /etc/kubernetes
      mode: "0750"
    - path: /etc/kubernetes/pki
      mode: "0750"
    - path: /var/lib/kubernetes
      mode: "0700"
    - path: /var/log/kubernetes
      mode: "0750"
