# ansible/k8s_base/tasks/1-prereqs.yml
---
- name: Copiar certificados dos CAs
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: kubernetes
    group: kubernetes
    mode: "0644"
    remote_src: true
  loop:
    - src: "{{ certs.ca_k8s.cert }}"
      dest: "/etc/kubernetes/pki/{{ certs.ca_k8s.cert | basename }}"
    - src: "{{ certs.ca_etcd.cert }}"
      dest: "/etc/kubernetes/pki/{{ certs.ca_etcd.cert | basename }}"
