# ansible/kube_apiserver/tasks/01-instalacao.yml
---
- name: Criar diretórios do Kubernetes no padrão Debian
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /var/lib/kubernetes
    - /var/log/kubernetes
    - /etc/kubernetes
    - /etc/kubernetes/ssl

- name: Baixar arquivo de checksum
  ansible.builtin.get_url:
    url: "{{ checksum_url }}"
    dest: "/tmp/kube-apiserver.sha256"
    mode: "0644"

- name: Ler checksum do arquivo
  ansible.builtin.shell: |
    cat /tmp/kube-apiserver.sha256 | tr -d '\n'
  register: kube_apiserver_checksum
  changed_when: false

- name: Baixar binário do kube-apiserver
  ansible.builtin.get_url:
    url: "{{ download_url }}"
    dest: "/usr/local/bin/kube-apiserver"
    mode: "0755"
    checksum: "sha256:{{ kube_apiserver_checksum.stdout }}"

- name: Criar usuário kubernetes
  ansible.builtin.user:
    name: kubernetes
    system: true
    shell: /usr/sbin/nologin
    home: /var/lib/kubernetes
    create_home: false

- name: Ajustar permissões dos diretórios
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: kubernetes
    group: kubernetes
    mode: "{{ item.mode }}"
  loop:
    - path: /var/lib/kubernetes
      mode: "0700"
    - path: /var/log/kubernetes
      mode: "0750"
    - path: /etc/kubernetes
      mode: "0750"
    - path: /etc/kubernetes/ssl
      mode: "0750"

- name: Criar arquivos de log
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    owner: etcd
    group: etcd
    mode: "0640"
  loop:
    - /var/log/kubernetes/apiserver.log
    - /var/log/kubernetes/apiserver.err
    - /var/log/kubernetes/apiserver.log

- name: Configurar logrotate para o kube-apiserver
  ansible.builtin.template:
    src: kube-apiserver.logrotate.j2
    dest: /etc/logrotate.d/kube-apiserver
    mode: '0644'
    owner: root
    group: root