# ansible/kube_apiserver/tasks/main.yml
---
- name: Instalar kube-apiserver
  ansible.builtin.import_tasks: 01-instalacao.yml
  tags:
    - kube-apiserver
    - kube-apiserver:pacotes

- name: Configurar certificados do kube-apiserver
  ansible.builtin.import_tasks: 02-pki.yml
  tags:
    - kube-apiserver
    - kube-apiserver:pki

- name: Configurar serviço do kube-apiserver
  ansible.builtin.import_tasks: 03-configuracao.yml
  tags:
    - kube-apiserver
    - kube-apiserver:configuracao