# ansible/monitoramento_nos/tasks/02-promtail.yml
---
- name: Instalar GnuPG
  ansible.builtin.apt:
    name: gnupg
    state: present

- name: Adicionar chave GPG do Grafana (caso não exista)
  ansible.builtin.apt_key:
    url: https://apt.grafana.com/gpg.key
    keyring: /usr/share/keyrings/grafana.gpg
    state: present

- name: Adicionar repositório do Grafana (caso não exista)
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    filename: grafana
    state: present

- name: Instalar Promtail
  ansible.builtin.apt:
    name: "promtail={{ versao_promtail }}"
    state: present

- name: Configurar Promtail
  ansible.builtin.template:
    src: promtail.yml.j2
    dest: /etc/promtail/config.yml
    mode: "0644"
  notify: Reiniciar Promtail

- name: Criar diretório de positions
  ansible.builtin.file:
    path: /var/lib/promtail
    state: directory
    owner: promtail
    mode: "0755"
  notify: Reiniciar Promtail

- name: Adicionar promtail aos grupos necessários
  ansible.builtin.user:
    name: promtail
    groups: 
      - systemd-journal
      - adm
    append: yes

- name: Configurar acesso ao journal
  ansible.builtin.file:
    path: /var/log/journal
    state: directory
    mode: "2775"
    group: systemd-journal

- name: Garantir serviço ativo
  ansible.builtin.systemd:
    name: promtail
    state: started
    enabled: true