# ansible/monitoramento_nos/tasks/main.yml
---
- name: Instalação do Node Exporter
  ansible.builtin.import_tasks: 01-node_exporter.yml
  tags: 
    - monitoramento_nos
    - monitoramento_nos:node_exporter

- name: Instalação e configuração do Promtail
  ansible.builtin.import_tasks: 02-promtail.yml
  tags:
    - monitoramento_nos
    - monitoramento_nos:promtail