# ansible/monitoramento_nos/tasks/main.yml
---
- name: Instalação do Node Exporter
  ansible.builtin.import_tasks: 01-instalacao.yml
  tags: 
    - monitoramento_nos
    - monitoramento_nos:pacotes

- name: Configuração do Node Exporter
  ansible.builtin.import_tasks: 02-configuracao.yml
  tags:
    - monitoramento_nos
    - monitoramento_nos:configuracao